version: "3.6"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg11
    # volumes: 
    #   - ./data:/var/lib/postgresql/data
    ports:
      - "5432-5435:5432"
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    networks:
      - timescaledb_cluster

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - timescaledb_cluster
    volumes:
      - ./etcd/conf/etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml

  haproxy:
    image: haproxy:1.9.8-alpine
    volumes: 
      - ./haproxy:/usr/local/etc/haproxy:ro
    networks:
      - timescaledb_cluster


  # grafana:
  #   image: grafana/grafana
  #   container_name: monitor
  #   ports: 
  #     - 5500:3000
  #   networks: 
  #     - timescaledb_cluster

networks:
  timescaledb_cluster:
    driver: bridge
    name: timescaledb_cluster